### ISSUE TITLE
启动报错！！！关于crossoverJie/SSM项目中对dubbo的使用

### ISSUE THREAD

**Issue by GitHub-Zany** [crossoverJie/SSM#1]
前两天clone了作者的SSM项目，在本地尝试运行一直报错，最后发现是jar依赖问题，经过漫长的排查发现是alibaba的dubbo-2.5.3.jar依赖的jar包下存在spring-2.5.6.SEC03.jar导致的报错，具体原因推测应该是spring-2.5.6.SEC03.jar的版本过低，导致与springframework的spring-core-4.1.4.RELEASE.jar有冲突。现将报错详情贴上：
严重: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
java.lang.NoSuchMethodError: org.springframework.core.CollectionFactory.createConcurrentMapIfPossible(I)Ljava/util/Map;
        at org.springframework.web.context.ContextLoader.<clinit>(ContextLoader.java:153)
        at org.springframework.web.context.ContextLoaderListener.createContextLoader(ContextLoaderListener.java:53)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:44)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4760)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5184)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:919)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1704)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Tip：alibaba已经放弃了对dubbo的更新，建议作者选择其他替代。
SSM的pom文件中依赖的activemq-all-5.13.3.jar本身依赖有slf4j-log4j12-1.7.13.jar，和pom文件中依赖的slf4j-log4j12-1.7.21.jar也有jar包冲突，可去除对slf4j-log4j12-1.7.21.jar的依赖解决

请晓！

**Comment by xmaxing** [comment]
感谢楼上分享，帮助很大，终于把项目跑起来了！！

**Comment by crossoverJie** [comment]
> 我本地是能跑起来的，所以这点我倒是没有注意，之后会把dubbo的依赖去掉。
