### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by koonchen** [crossoverJie/SSM#33]
### 版本

本地 redis 版本: stable 4.0.9

### 预期结果

期望运行 ssm-web

### 实际结果

```shell
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisTemplate' defined in class path resource [spring-mybatis.xml]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.springframework.core.serializer.support.DeserializingConverter.<init>(Ljava/lang/ClassLoader;)V
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 99 more
Caused by: java.lang.NoSuchMethodError: org.springframework.core.serializer.support.DeserializingConverter.<init>(Ljava/lang/ClassLoader;)V
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.<init>(JdkSerializationRedisSerializer.java:54)
	at org.springframework.data.redis.core.RedisTemplate.afterPropertiesSet(RedisTemplate.java:122)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1625)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1562)
	... 106 more
...
```

### 重现结果的步骤

仅将 ssm-web 部署，本地 redis 正常运行，数据库未报错，但是出现如上错误，查阅得知是 spring 版本不符？

**Comment by koonchen** [comment]
这个问题已解决，但是不知道为什么...

根据提示搜出的结果是 spring 的版本太低（ ssm-web 的 spring 版本是 4.1.4）于是我将之设置为 4.3.7 ，得到的结果是另一个错误：

```shell
java.lang.NoSuchMethodError: org.springframework.aop.framework.AopProxyUtils.getSingletonTarget(Ljava/lang/Object;)Ljava/lang/Object;
```

反正是说版本还是错了，于是我将之设置为 4.2.4 版本，成功运行。

仅仅将：

```
https://github.com/crossoverJie/SSM/blob/b2107a78a7d761f9873b736ba5541ecb602e7d66/SSM-WEB/pom.xml#L46
```

改为：

```java
<spring.version>4.2.4.RELEASE</spring.version>
```

**Comment by crossoverJie** [comment]
@koonchen 我本地测试下，明天给你回复哈。

**Comment by crossoverJie** [comment]
@koonchen 我本地测了下，问题没有复现。

![2.jpg](https://i.loli.net/2018/05/25/5b07702601c6a.jpg)

你可以尝试 `mvn clean package` maven 有时候打包也会抽风(初步估计是你包没有下载完)：

![1.png](https://i.loli.net/2018/05/25/5b0770799c16d.png)

之后用 `Tomcat7` 的插件来启动试下:

![3.jpg](https://i.loli.net/2018/05/25/5b0770da06d2f.jpg)

**Comment by koonchen** [comment]
我读了 [issues#28](https://github.com/crossoverJie/SSM/issues/28) ，并且将代码还原，发现是一样的问题：

```shell
[ERROR] Failed to execute goal on project SSM-WEB: Could not resolve dependencies for project com.crossoverJie:SSM-WEB:war:2.2.0-SNAPSHOT: Failed to collect dependencies at com.crossoverJie:SSM-API:jar:2.2.0-SNAPSHOT: Failed to read artifact descriptor for com.crossoverJie:SSM-API:jar:2.2.0-SNAPSHOT: Could not find artifact com.crossoverJie:SSM:pom:2.2.0-SNAPSHOT -> [Help 1]
```

我根据这位大兄弟的方法做了一遍，包括手动安装 ssm-api :

```
~/.m2/rep…ory/com/crossoverJie
|____SSM-REQUEST-CHECK
| |____1.0.0-SNAPSHOT
| | |____SSM-REQUEST-CHECK-1.0.0-SNAPSHOT.jar
| | |____SSM-REQUEST-CHECK-1.0.0-SNAPSHOT.pom
| | |_____remote.repositories
| | |____maven-metadata-local.xml
| |____maven-metadata-local.xml
|____SSM-DUBBO-HTTP
| |____1.0.0
| | |____SSM-DUBBO-HTTP-1.0.0.pom
| | |_____remote.repositories
| |____maven-metadata-local.xml
|____SSM-TRACE-FILTER
| |____1.0.0
| | |____SSM-TRACE-FILTER-1.0.0.jar
| | |____SSM-TRACE-FILTER-1.0.0.pom
| | |____SSM-TRACE-FILTER-1.0.0.jar.lastUpdated
| | |____SSM-TRACE-FILTER-1.0.0.pom.lastUpdated
| | |_____remote.repositories
| |____maven-metadata-local.xml
|____SSM-API
| |____2.2.0-SNAPSHOT
| | |____SSM-API-2.2.0-SNAPSHOT.jar
| | |____SSM-API-2.2.0-SNAPSHOT.pom
| | |_____remote.repositories
| | |____maven-metadata-local.xml
| |____maven-metadata-local.xml
|____SSM-DUBBO-FILTER
| |____1.0.0
| | |____SSM-DUBBO-FILTER-1.0.0.pom
| | |_____remote.repositories
| |____maven-metadata-local.xml
|____SSM-HTTP-PROVIDER
| |____1.0.0
| | |____SSM-HTTP-PROVIDER-1.0.0.pom
| | |____SSM-HTTP-PROVIDER-1.0.0.jar
| | |_____remote.repositories
| | |____SSM-HTTP-PROVIDER-1.0.0.jar.lastUpdated
| | |____SSM-HTTP-PROVIDER-1.0.0.pom.lastUpdated
| |____maven-metadata-local.xml
```

尝试了在 ssm-web 下使用 `clean` 和 `package` 的各种排列组合，错误依旧；在 ssm 下使用 `clean` 和 `package` 还后出现 `java.lang.NoSuchMethodError` 的错误，然后我将 ssm-web 下 spring 更换成 4.2.4 ，再次在 ssm 下一起运行 `clean` `package` ，过了 ￣□￣｜｜。

现在 ssm-web 下运行  `clean` `package` 还是会出现上面提及的 `[ERROR] Failed to execute goal on project SSM-WEB` 。（现在使用 `tomcat7:run-war` 也出现这个错误）

已经用右上角 `run/debug configurations` 里放的 tomcat 运行了，开始愉快地学习😁

这是一个无伤大雅的错误，不求甚解。谢谢 @crossoverJie 的解答。

**Comment by mousepotato** [comment]
感谢 @crossoverJie 分享这么好的代码。

我第一次下载安装编译。反馈一下哈：

1. 也是提示 NoSuchMethodError 问题，修改 <spring.version>4.2.4.RELEASE</spring.version> 问题解决。
2. 请问“SSM-TRACE-FILTER” 和 “SSM-HTTP-PROVIDER” 这两个jar包在哪里可以编译，我使用 mvn clean package 时提示找不到这两个jar文件。

![image](https://user-images.githubusercontent.com/97764/40871058-6fa43db6-65e9-11e8-9855-b5af31a1385a.png)

3. 包 com.crossoverJie.controller下RedisController.java 里面的 CheckReqNo annotation 提示找不到。
![image](https://user-images.githubusercontent.com/97764/40871074-a4a40186-65e9-11e8-9f64-a64601e09b0d.png)

谢谢。
